  /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include "stm32f103xx_gpio_driver.h"


//void delay(void){
	//for(uint32_t i=0; i<500000 ; i++);
//}


int main(void){

	GPIO_PinConfig_t myGPIO, myGPIO2;
 	myGPIO.port = GPIOC;
	myGPIO.pin = 13;
	myGPIO.mode = OUTPUT_MODE;
	myGPIO.mode_type = GPIO_OUT_PUSHPULL;
	myGPIO.speed = GPIO_MODE_OUT_50MHz;

	myGPIO2.port = GPIOA;
	myGPIO2.pin = 5;
	myGPIO2.mode = OUTPUT_MODE;
	myGPIO2.mode_type = GPIO_OUT_PUSHPULL;
	myGPIO2.speed = GPIO_MODE_OUT_50MHz;

	gpio_init(&myGPIO, ENABLE);
	gpio_init(&myGPIO2, ENABLE);

	configure_gpio_interrupt(GPIOB, 4, RISING_EDGE);
	enable_gpio_interrupt(4, EXTI4_IRQn);

	while(1){
		gpio_toggle(GPIOC, 13);
		for(uint32_t i=0; i<500000 ; i++);
		//delay();
	}



	return 0;
}




void EXTI4_IRQHandler() {
	clear_gpio_interrupt(4);
	gpio_toggle(GPIOA, 5);
	for(uint32_t i=0; i<500000 ; i++);
}






